project_id = "pgfgripuanuwwolmtknn"

[functions.upload-image]
verify_jwt = false

[functions.update-secret]
verify_jwt = false

[functions.extract-google-reviews]
verify_jwt = false

[functions.extract-product-data]
verify_jwt = false

[functions.moderate-reviews]
verify_jwt = false