project_id = "pgfgripuanuwwolmtknn"

[functions.import-loja-integrada-api]
verify_jwt = true

[functions.export-product-ai-playbook]
verify_jwt = false

[functions.generate-merchant-feed]
verify_jwt = false

[functions.strategic-blog-generator]
verify_jwt = false

[functions.ai-content-generator]
verify_jwt = false

[functions.generate-product-ai-content]
verify_jwt = false

[functions.migrate-products-to-repository]
verify_jwt = false

[functions.upload-image]
verify_jwt = true

[functions.update-secret]
verify_jwt = true

[functions.extract-google-reviews]
verify_jwt = true

[functions.extract-product-data]
verify_jwt = true

[functions.moderate-reviews]
verify_jwt = true

[functions.ai-seo-generator]
verify_jwt = true

[functions.generate-sitemap]
verify_jwt = false

[functions.validate-schema]
verify_jwt = true

[functions.test-ftp-connection]
verify_jwt = false

[functions.test-wordpress-connection]
verify_jwt = false

[functions.publish-blog-post]
verify_jwt = true

[functions.migrate-video-data]
verify_jwt = false

[functions.extract-youtube-captions]
verify_jwt = false

[functions.export-google-ads-csv]
verify_jwt = false

[functions.generate-ad-copies]
verify_jwt = false

[functions.cloudflare-direct-upload]
verify_jwt = false

[functions.import-repository-csv]
verify_jwt = true

[functions.generate-social-content]
verify_jwt = false

[functions.generate-tiktok-content]
verify_jwt = false

[functions.generate-robots-txt]
verify_jwt = false

[functions.generate-video-sitemap]
verify_jwt = false

[functions.auto-seo-enhancer]
verify_jwt = true

[functions.exchange-oauth-code]
verify_jwt = true

[functions.test-youtube-connection]
verify_jwt = true

[functions.test-google-business-connection]
verify_jwt = true