
UPDATE company_profile
SET seo_domains = COALESCE(seo_domains, '[]'::jsonb) || '[
  {"name": "Rayshape", "domain": "rayshape.com.br", "cloudflare_project_name": "rayshape", "cloudflare_enabled": true, "cloudflare_status": "pending", "use_for_seo": true, "use_for_schema": true, "use_for_footer": false, "tracking_pixels": {"gtm": {"enabled": false, "container_id": ""}, "ga4": {"enabled": false, "measurement_id": ""}, "meta": {"enabled": false, "pixel_id": ""}, "tiktok": {"enabled": false, "pixel_id": ""}}},
  {"name": "Rayshape 3D", "domain": "rayshape3d.com.br", "cloudflare_project_name": "rayshape3d", "cloudflare_enabled": true, "cloudflare_status": "pending", "use_for_seo": true, "use_for_schema": true, "use_for_footer": false, "tracking_pixels": {"gtm": {"enabled": false, "container_id": ""}, "ga4": {"enabled": false, "measurement_id": ""}, "meta": {"enabled": false, "pixel_id": ""}, "tiktok": {"enabled": false, "pixel_id": ""}}},
  {"name": "Truio Connect", "domain": "truioconnect.com.br", "cloudflare_project_name": "truioconnect", "cloudflare_enabled": true, "cloudflare_status": "pending", "use_for_seo": true, "use_for_schema": true, "use_for_footer": false, "tracking_pixels": {"gtm": {"enabled": false, "container_id": ""}, "ga4": {"enabled": false, "measurement_id": ""}, "meta": {"enabled": false, "pixel_id": ""}, "tiktok": {"enabled": false, "pixel_id": ""}}},
  {"name": "BLZ Dental", "domain": "blzdental.com.br", "cloudflare_project_name": "blzdental", "cloudflare_enabled": true, "cloudflare_status": "pending", "use_for_seo": true, "use_for_schema": true, "use_for_footer": false, "tracking_pixels": {"gtm": {"enabled": false, "container_id": ""}, "ga4": {"enabled": false, "measurement_id": ""}, "meta": {"enabled": false, "pixel_id": ""}, "tiktok": {"enabled": false, "pixel_id": ""}}},
  {"name": "Mediti 900 Global", "domain": "mediti900.com", "cloudflare_project_name": "mediti900-global", "cloudflare_enabled": true, "cloudflare_status": "pending", "use_for_seo": true, "use_for_schema": true, "use_for_footer": false, "tracking_pixels": {"gtm": {"enabled": false, "container_id": ""}, "ga4": {"enabled": false, "measurement_id": ""}, "meta": {"enabled": false, "pixel_id": ""}, "tiktok": {"enabled": false, "pixel_id": ""}}},
  {"name": "Mediti 700", "domain": "mediti700.com.br", "cloudflare_project_name": "mediti700", "cloudflare_enabled": true, "cloudflare_status": "pending", "use_for_seo": true, "use_for_schema": true, "use_for_footer": false, "tracking_pixels": {"gtm": {"enabled": false, "container_id": ""}, "ga4": {"enabled": false, "measurement_id": ""}, "meta": {"enabled": false, "pixel_id": ""}, "tiktok": {"enabled": false, "pixel_id": ""}}},
  {"name": "Mediti 600", "domain": "mediti600.com.br", "cloudflare_project_name": "mediti600", "cloudflare_enabled": true, "cloudflare_status": "pending", "use_for_seo": true, "use_for_schema": true, "use_for_footer": false, "tracking_pixels": {"gtm": {"enabled": false, "container_id": ""}, "ga4": {"enabled": false, "measurement_id": ""}, "meta": {"enabled": false, "pixel_id": ""}, "tiktok": {"enabled": false, "pixel_id": ""}}},
  {"name": "E-Odonto", "domain": "eodonto.com", "cloudflare_project_name": "eodonto", "cloudflare_enabled": true, "cloudflare_status": "pending", "use_for_seo": true, "use_for_schema": true, "use_for_footer": false, "tracking_pixels": {"gtm": {"enabled": false, "container_id": ""}, "ga4": {"enabled": false, "measurement_id": ""}, "meta": {"enabled": false, "pixel_id": ""}, "tiktok": {"enabled": false, "pixel_id": ""}}},
  {"name": "Dentala", "domain": "dentala.com.br", "cloudflare_project_name": "dentala", "cloudflare_enabled": true, "cloudflare_status": "pending", "use_for_seo": true, "use_for_schema": true, "use_for_footer": false, "tracking_pixels": {"gtm": {"enabled": false, "container_id": ""}, "ga4": {"enabled": false, "measurement_id": ""}, "meta": {"enabled": false, "pixel_id": ""}, "tiktok": {"enabled": false, "pixel_id": ""}}},
  {"name": "Labtech Dent", "domain": "labtechdent.com.br", "cloudflare_project_name": "labtechdent", "cloudflare_enabled": true, "cloudflare_status": "pending", "use_for_seo": true, "use_for_schema": true, "use_for_footer": false, "tracking_pixels": {"gtm": {"enabled": false, "container_id": ""}, "ga4": {"enabled": false, "measurement_id": ""}, "meta": {"enabled": false, "pixel_id": ""}, "tiktok": {"enabled": false, "pixel_id": ""}}},
  {"name": "PrintSafe BR", "domain": "printsafebr.com.br", "cloudflare_project_name": "printsafebr", "cloudflare_enabled": true, "cloudflare_status": "pending", "use_for_seo": true, "use_for_schema": true, "use_for_footer": false, "tracking_pixels": {"gtm": {"enabled": false, "container_id": ""}, "ga4": {"enabled": false, "measurement_id": ""}, "meta": {"enabled": false, "pixel_id": ""}, "tiktok": {"enabled": false, "pixel_id": ""}}}
]'::jsonb,
updated_at = now()
WHERE id = (SELECT id FROM company_profile LIMIT 1);
